package org.emau.icmvc.ttp.psn.selenium;

/*-
 * ###license-information-start###
 * gPAS - a Generic Pseudonym Administration Service
 * __
 * Copyright (C) 2013 - 2024 Independent Trusted Third Party of the University Medicine Greifswald
 * 							kontakt-ths@uni-greifswald.de
 * 							concept and implementation
 * 							l.geidel
 * 							web client
 * 							a.blumentritt
 * 							docker
 * 							r.schuldt
 * 							please cite our publications
 * 							http://dx.doi.org/10.3414/ME14-01-0133
 * 							http://dx.doi.org/10.1186/s12967-015-0545-6
 * __
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * ###license-information-end###
 */

// Generated by Selenium IDE

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;

@Tag("Selenium")
public class SampleSeleniumTest extends AbstractSeleniumTest
{
	@Test
	public void test() {
		// add psn
		driver.get(getTestUrl("gpas-web/html/internal/edit.xhtml"));
		driver.manage().window().setSize(new Dimension(1520, 1400));

		assertElementExists(By.cssSelector("#main\\3Aj_idt125 > .ui-button-text"), true);
		assertElementExists(By.id("newPsn:newPseudonymDomain_label"), true);
		assertElementExists(By.id("newPsn:newPseudonymDomain_1"), true);
		assertElementExists(By.id("newPsn:newPseudonymOriginalValue"), true);
		assertElementExists(By.id("newPsn:newPseudonymOriginalValue"), false).sendKeys("head7574");
		assertElementExists(By.cssSelector("#newPsn\\3Aj_idt198 > .ui-button-text"), true);

		// delete psn
		driver.get(getTestUrl("gpas-web/html/internal/edit.xhtml"));
		driver.manage().window().setSize(new Dimension(1520, 1400));

		assertElementExists(By.xpath("//tr[2]/td"), true);
		assertElementExists(By.xpath("//td[contains(.,'head7574')]"), true);
		assertElementExists(By.xpath("//body/div[@id='main:pseudonyms_menu']/ul[1]/li[11]/a[1]"), true);
		assertElementExists(By.xpath("//body/div[@id='site']/div[@id='middle-column']/div[1]/div[4]/div[2]/form[1]/button[1]/span[2]"), true);

//		{
//			WebElement element = driver.findElement(By.cssSelector(".ui-button-text:nth-child(3)"));
//			Actions builder = new Actions(driver);
//			builder.moveToElement(element).perform();
//		}
	}
}
